mutation AddMovieToList($listId: UUID!, $movieId: UUID!, $note: String, $position: Int!) @auth(level: USER) {
  listMovie_insert(data: {listId: $listId, movieId: $movieId, note: $note, position: $position})
}

query GetMoviesInList($listId: UUID!) @auth(level: USER) {
  list(id: $listId) {
    movies_via_ListMovie {
      id
      title
      year
      genres
      runtime
      summary
    }
  }
}

mutation CreateNewList($name: String!, $description: String, $public: Boolean!) @auth(level: USER) {
  list_insert(data: {name: $name, description: $description, public: $public, userId_expr: "auth.uid", createdAt_expr: "request.time", updatedAt_expr: "request.time"})
}

query GetMyLists @auth(level: USER) {
  lists(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    name
    description
    public
    createdAt
    updatedAt
  }
}